import AppContextProvider from '@/components/AppContext'
import type { Metadata } from 'next'
import { ReactNode } from 'react'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="dark">
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  )
}
