import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import AppContextProvider from '@/components/AppContext'
import EventBusContextProvider from '@/components/EventBusContext'
import '@/styles/globals.css'
import '@/styles/markdown.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>ChatGPT</title>
        <link rel="icon" href="/icons/favicon.png" type="image/png" sizes="32x32" />
      </head>
      <body>
        <AppContextProvider>
          <EventBusContextProvider>{children}</EventBusContextProvider>
        </AppContextProvider>
      </body>
    </html>
  )
}
